save_thumbnail_image:
  name: Save Thumbnail Image
  description: "Request the latest motion thumbnail from a camera and write it to a file"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to get thumbnail from
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    filename:
      name: Filename
      description: "string (required) where to save the thumbnail"
      required: true
      selector:
        text:
      example: "/config/www/thumbnail.png"
    image_width:
      name: Image Width
      description: "string (optional) width of Thumbnail image in pixels"
      example: 640
      selector:
        number:
set_recording_mode:
  name: Set Recording Mode
  description: "Set recording mode for the camera"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to set recording mode mode for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    recording_mode:
      name: Recording Mode
      description: "(Required) Valid options are: always = Always Recording, motion = Only record on motion, never = stop recording, smart = Smart Detect. Default value is: motion"
      required: true
      example: motion
      selector:
        select:
          options:
            - "always"
            - "motion"
            - "smart"
            - "never"
set_ir_mode:
  name: Set Infrared mode
  description: "Set Infrared Settings for the camera"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to set IR mode for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    ir_mode:
      name: IR Mode
      description: "(Optional) Valid options are: always_on = IR always on, auto = Automatic, led_off = Automatic wo LEDs, always_off = Always Off. Default value is: auto"
      example: auto
      selector:
        select:
          options:
            - "always_on"
            - "auto"
            - "led_off"
            - "always_off"
set_status_light:
  name: Set Status Lights
  description: "Turn the Cameras Led Light on or off"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to change status light on
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    light_on:
      name: Light on
      description: "(Optional) Valid options are: true or false"
      example: true
      selector:
        boolean:
set_hdr_mode:
  name: Set High Dynamic Range mode (HDR)
  description: "Turn the Cameras HDR mode on or off"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to change hdr mode for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    hdr_on:
      name: HDR mode on
      description: "(Optional) Valid options are: true or false"
      example: true
      selector:
        boolean:
set_highfps_video_mode:
  name: Set High FPS video mode
  description: "Turn the Cameras High FPS mode on or off (Only G4 Cameras)"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to change video mode for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    high_fps_on:
      name: High FPS on
      description: "(Optional) Valid options are: true or false"
      example: true
      selector:
        boolean:
set_doorbell_lcd_message:
  name: Set Doorbell LCD message
  description: "Display a message on the LCD Screen on the G4 Doorbell"
  fields:
    entity_id:
      name: Entity ID
      description: (Required) Doorbell to display message on
      example: "camera.doorbell"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    message:
      name: Message to display
      description: (Required) Message to display on LCD Panel. Max 30 characters
      example: Ring the bell
      required: true
      selector:
        text:
    duration:
      name: Duration (minutes)
      description: "(Optional) Number of minutes to display message, before returning to default. Leave blank to display always"
      example: 5
      selector:
        number:
          min: 1
          max: 120
          step: 1
          mode: slider
set_mic_volume:
  name: Set microphone volume
  description: "Sets the microphone sensitivity volume"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to change volume level for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    level:
      name: Microphone Level
      description: "(Required) Number between 0 and 100 (0 equals off)"
      example: 75
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
set_privacy_mode:
  name: Set Privacy Mode
  description: "Enables or disables a full cover Privacy Zone for the Camera"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to set privacy mode for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    privacy_mode:
      name: Privacy mode
      description: "(Required) Valid options are: true or false"
      example: true
      selector:
        boolean:
    mic_level:
      name: Microphone Level
      description: "(Optional) Microphone Level, a number between 0 and 100 (0 equals off) Default is no change"
      example: 75
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
    recording_mode:
      name: Recording mode
      description: "(Optional) Valid options are: always = Always Recording, motion = Only record on motion, never = stop recording, smart = Smart Detect. Default value is: no change"
      example: motion
      selector:
        select:
          options:
            - "always"
            - "motion"
            - "smart"
            - "never"
set_zoom_position:
  name: Set Zoom Position
  description: "Sets the cameras optical Zoom Position"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to change zoom position for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    position:
      name: Position
      description: "(Required) Number between 0 and 100 (0 equals no zoom)"
      example: 25
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
set_wdr_value:
  name: Set Wide Dynamic Range (WDR)
  description: "Sets the cameras Wide Dynamic Range value"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to change wdr for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    value:
      name: Value
      description: "(Required) Number between 0 and 3 (0 equals disabled). Default value is 1."
      example: 1
      selector:
        number:
          min: 0
          max: 3
          step: 1
          mode: slider
light_settings:
  name: Light Settings
  description: "Adjust settings on a UniFi attached Floodlight"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) floodlight to adjust settings for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: light
    mode:
      name: Mode
      description: "string (required) When to turn on light at Motion, where off is never, motion is on motion detection and dark is only when it is dark outside."
      example: "motion"
      required: true
      selector:
        select:
          options:
            - "off"
            - "motion"
            - "dark"
    enable_at:
      name: Enable At
      description: "string (optional) When motion is selected as mode, one can adjust if light turns on on motion detection. Where fulltime is always, and dark is only when dark."
      example: "fulltime"
      selector:
        select:
          options:
            - "fulltime"
            - "dark"
    duration:
      name: Duration
      description: "int (optional) Number of seconds the light stays turned on. Must be one of these values: 15, 30, 60, 300, 900."
      example: 60
      selector:
        select:
          options:
            - "15"
            - "30"
            - "60"
            - "300"
            - "900"
    sensitivity:
      name: Sensitivity
      description: "int (optional) Motion sensitivity of the PIR. Must be a number between 1 and 100."
      example: 80
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
set_doorbell_chime_duration:
  name: Set the Chime duration attached to a Doorbell
  description: "Set the duration for doorbell chime"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) doorbell with chime attached
      example: "camera.doorbell"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    chime_duration:
      name: Chime duration
      description: "(required) Valid options are: 0 to 10000 (0 is No Chime)"
      required: true
      example: 300
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          mode: slider
