save_thumbnail_image:
  description: "Request the latest motion thumbnail from a camera and write it to a file"
  fields:
    entity_id:
      description: "string (required) camera to get thumbnail from"
      example: "camera.outdoor"
    filename:
      description: "string (required) where to save the thumbnail"
      example: "/config/www/thumbnail.png"
    image_width:
      description: "string (optional) width of Thumbnail image in pixels"
      example: "640"
set_recording_mode:
  description: "Set recording mode for the camera"
  fields:
    entity_id:
      description: "string (required) camera to enable recording on"
      example: "camera.outdoor"
    recording_mode:
      description: "(Optional) Valid options are: always = Always Recording, motion = Only record on motion, never = stop recording, smart = Smart Detect. Default value is: motion"
      example: motion
set_ir_mode:
  description: "Set Infrared Settings for the camera"
  fields:
    entity_id:
      description: "string (required) camera to set IR mode for"
      example: "camera.outdoor"
    ir_mode:
      description: "(Optional) Valid options are: always_on = IR always on, auto = Automatic, led_off = Automatic wo LEDs, always_off = Always Off. Default value is: auto"
      example: auto
set_status_light:
  description: "Turn the Cameras Led Light on or off"
  fields:
    entity_id:
      description: "string (required) camera to change status light on"
      example: "camera.outdoor"
    light_on:
      description: "(Optional) Valid options are: true or false"
      example: true
set_hdr_mode:
  description: "Turn the Cameras HDR mode on or off"
  fields:
    entity_id:
      description: "string (required) camera to change hdr mode for"
      example: "camera.outdoor"
    hdr_on:
      description: "(Optional) Valid options are: true or false"
      example: true
set_highfps_video_mode:
  description: "Turn the Cameras High FPS mode on or off (Only G4 Cameras)"
  fields:
    entity_id:
      description: "string (required) camera to change video mode for"
      example: "camera.outdoor"
    high_fps_on:
      description: "(Optional) Valid options are: true or false"
      example: true
set_doorbell_lcd_message:
  description: "Display a message on the LCD Screen on the G4 Doorbell"
  fields:
    entity_id:
      description: "(Required) Doorbell to display message on"
      example: "camera.doorbell"
    message:
      description: "(Required) Message to display on LCD Panel"
      example: Ring the bell
    duration:
      description: "(Optional) Number of minutes to display message, before returning to default. Leave blank to display always"
      example: "15"
set_mic_volume:
  description: "Sets the microphone sensitivity volume"
  fields:
    entity_id:
      description: "string (required) camera to change volume level for"
      example: "camera.outdoor"
    level:
      description: "(Required) Number between 0 and 100 (0 equals off)"
      example: "75"
set_privacy_mode:
  description: "Enables or disables a full cover Privacy Zone for the Camera"
  fields:
    entity_id:
      description: "string (required) camera to set privacy mode for"
      example: "camera.outdoor"
    privacy_mode:
      description: "(Required) Valid options are: true or false"
      example: true
    mic_level:
      description: "(Optional) Microphone Level, a number between 0 and 100 (0 equals off) Default is no change"
      example: "75"
    recording_mode:
      description: "(Optional) Valid options are: always = Always Recording, motion = Only record on motion, never = stop recording, smart = Smart Detect. Default value is: no change"
      example: motion
set_zoom_position:
  description: "Sets the cameras optical Zoom Position"
  fields:
    entity_id:
      description: "string (required) camera to change zoom position for"
      example: "camera.outdoor"
    position:
      description: "(Required) Number between 0 and 100 (0 equals no zoom)"
      example: "25"
light_settings:
  description: "Adjust settings on a UniFi attached Floodlight"
  fields:
    entity_id:
      description: "string (required) light to adjust settings for"
      example: "light.floodlight"
    mode:
      description: "string (required) When to turn on light at Motion, where off is never, motion is on motion detection and dark is only when it is dark outside."
      example: "motion"
    enable_at:
      description: "string (optional) When motion is selected as mode, one can adjust if light turns on on motion detection. Where fulltime is always, and dark is only when dark."
      example: "fulltime"
    duration:
      description: "int (optional) Number of seconds the light stays turned on. Must be one of these values: 15, 30, 60, 300, 900."
      example: "60"
    sensitivity:
      description: "int (optional) Motion sensitivity of the PIR. Must be a number between 1 and 100."
      example: "80"

