save_thumbnail_image:
  description: "Request the latest motion thumbnail from a camera and write it to a file"
  fields:
    entity_id:
      description: "string (required) camera to get thumbnail from"
      example: "camera.outdoor"
    filename:
      description: "string (required) where to save the thumbnail"
      example: "/config/www/thumbnail.png"
    image_width:
      description: "string (optional) width of Thumbnail image in pixels"
      example: "640"
set_recording_mode:
  description: "Set recording mode for the camera"
  fields:
    entity_id:
      description: "string (required) camera to enable recording on"
      example: "camera.outdoor"
    recording_mode:
      description: "(Optional) Valid options are: always = Always Recording, motion = Only record on motion, never = stop recording, smart = Smart Detect. Default value is: motion"
      example: motion
set_ir_mode:
  description: "Set Infrared Settings for the camera"
  fields:
    entity_id:
      description: "string (required) camera to set IR mode for"
      example: "camera.outdoor"
    ir_mode:
      description: "(Optional) Valid options are: always_on = IR always on, auto = Automatic, led_off = Automatic wo LEDs, always_off = Always Off. Default value is: auto"
      example: auto
set_status_light:
  description: "Turn the Cameras Led Light on or off"
  fields:
    entity_id:
      description: "string (required) camera to change status light on"
      example: "camera.outdoor"
    light_on:
      description: "(Optional) Valid options are: true or false"
      example: true
set_hdr_mode:
  description: "Turn the Cameras HDR mode on or off"
  fields:
    entity_id:
      description: "string (required) camera to change hdr mode for"
      example: "camera.outdoor"
    hdr_on:
      description: "(Optional) Valid options are: true or false"
      example: true
set_highfps_video_mode:
  description: "Turn the Cameras High FPS mode on or off (Only G4 Cameras)"
  fields:
    entity_id:
      description: "string (required) camera to change video mode for"
      example: "camera.outdoor"
    high_fps_on:
      description: "(Optional) Valid options are: true or false"
      example: true
set_doorbell_lcd_message:
  description: Display a message on the LCD Screen on the G4 Doorbell"
  fields:
    entity_id:
      description: "(Required) Doorbell to display message on"
      example: "camera.doorbell"
    message:
      description: "(Required) Message to display on LCD Panel"
      example: Ring the bell
    duration:
      description: "(Optional) Number of minutes to display message, before returning to default. Leave blank to display always"
      example: "15"
